In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))
from src.data_loader import DataLoader

In [2]:
dataLoader = DataLoader()
dataLoader.download()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2016-02-25 00:00:00-05:00,1931.869995,1951.829956,1925.410034,1951.699951,4118210000,0.0,0.0
2016-02-26 00:00:00-05:00,1954.949951,1962.959961,1945.780029,1948.050049,4348510000,0.0,0.0
2016-02-29 00:00:00-05:00,1947.130005,1958.270020,1931.810059,1932.229980,4588180000,0.0,0.0
2016-03-01 00:00:00-05:00,1937.089966,1978.349976,1937.089966,1978.349976,4819750000,0.0,0.0
2016-03-02 00:00:00-05:00,1976.599976,1986.510010,1968.800049,1986.449951,4666610000,0.0,0.0
...,...,...,...,...,...,...,...
2026-02-18 00:00:00-05:00,6855.479980,6909.120117,6849.660156,6881.310059,5098160000,0.0,0.0
2026-02-19 00:00:00-05:00,6861.339844,6879.120117,6833.060059,6861.890137,5151690000,0.0,0.0
2026-02-20 00:00:00-05:00,6843.259766,6915.859863,6836.330078,6909.509766,5432480000,0.0,0.0
2026-02-23 00:00:00-05:00,6901.250000,6916.959961,6819.819824,6837.750000,5638350000,0.0,0.0
2026-02-24 00:00:00-05:00,6837.370117,6899.169922,6815.430176,6890.069824,5266090000,0.0,0.0

In [3]:
dataLoader.clean()

,Open,High,Low,Close,Volume,Tomorrow,Target
Date,,,,,,,
2016-02-25 00:00:00-05:00,1931.869995,1951.829956,1925.410034,1951.699951,4118210000,1948.050049,0
2016-02-26 00:00:00-05:00,1954.949951,1962.959961,1945.780029,1948.050049,4348510000,1932.229980,0
2016-02-29 00:00:00-05:00,1947.130005,1958.270020,1931.810059,1932.229980,4588180000,1978.349976,1
2016-03-01 00:00:00-05:00,1937.089966,1978.349976,1937.089966,1978.349976,4819750000,1986.449951,1
2016-03-02 00:00:00-05:00,1976.599976,1986.510010,1968.800049,1986.449951,4666610000,1993.400024,1
...,...,...,...,...,...,...,...
2026-02-18 00:00:00-05:00,6855.479980,6909.120117,6849.660156,6881.310059,5098160000,6861.890137,0
2026-02-19 00:00:00-05:00,6861.339844,6879.120117,6833.060059,6861.890137,5151690000,6909.509766,1
2026-02-20 00:00:00-05:00,6843.259766,6915.859863,6836.330078,6909.509766,5432480000,6837.750000,0
2026-02-23 00:00:00-05:00,6901.250000,6916.959961,6819.819824,6837.750000,5638350000,6890.069824,1
2026-02-24 00:00:00-05:00,6837.370117,6899.169922,6815.430176,6890.069824,5266090000,NaN,0

In [4]:
dataLoader.add_technical_indicators()

,Open,High,Low,Close,Volume,Tomorrow,Target,EMA_9,MACD,MACD_Signal,MACD_Histogram,ATR_14
Date,,,,,,,,,,,,
2016-02-25 00:00:00-05:00,1931.869995,1951.829956,1925.410034,1951.699951,4118210000,1948.050049,0,1951.699951,0.000000,0.000000,0.000000,NaN
2016-02-26 00:00:00-05:00,1954.949951,1962.959961,1945.780029,1948.050049,4348510000,1932.229980,0,1950.969971,-0.291160,-0.058232,-0.232928,NaN
2016-02-29 00:00:00-05:00,1947.130005,1958.270020,1931.810059,1932.229980,4588180000,1978.349976,1,1947.221973,-1.777959,-0.402177,-1.375782,NaN
2016-03-01 00:00:00-05:00,1937.089966,1978.349976,1937.089966,1978.349976,4819750000,1986.449951,1,1953.447573,0.756520,-0.170438,0.926958,NaN
2016-03-02 00:00:00-05:00,1976.599976,1986.510010,1968.800049,1986.449951,4666610000,1993.400024,1,1960.048049,3.379753,0.539600,2.840153,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-02-18 00:00:00-05:00,6855.479980,6909.120117,6849.660156,6881.310059,5098160000,6861.890137,0,6883.797111,-8.737314,1.834837,-10.572151,96.540806
2026-02-19 00:00:00-05:00,6861.339844,6879.120117,6833.060059,6861.890137,5151690000,6909.509766,1,6879.415716,-10.371058,-0.606342,-9.764716,91.270089
2026-02-20 00:00:00-05:00,6843.259766,6915.859863,6836.330078,6909.509766,5432480000,6837.750000,0,6885.434526,-7.734150,-2.031904,-5.702247,91.555804
2026-02-23 00:00:00-05:00,6901.250000,6916.959961,6819.819824,6837.750000,5638350000,6890.069824,1,6875.897621,-11.304485,-3.886420,-7.418065,92.952951
2026-02-24 00:00:00-05:00,6837.370117,6899.169922,6815.430176,6890.069824,5266090000,NaN,0,6878.732061,-9.799268,-5.068990,-4.730279,89.575056